export const loremIpsumSentences = [
    "Lorem ipsum dolor sit amet.",
    "Consectetur adipisicing elit.",
    "Quos, quidem.",
    "Quibusdam, quia?",
    "Quisquam, voluptatum.",
    "Quisqua, magni!",
    "Eos veniam, reiciendis!",
    "Nisi facere assumenda.",
    "Voluptate, earum.",
    "Maxime, possimus.",
    "Tempora eius, libero accusantium suscipit voluptas qui dolores repellat.",
    "Mollitia perspiciatis velit officia aliquid deserunt rem nobis, asperiores necessitatibus.",
    "Dolorum odit aperiam eligendi eius pariatur quaerat ipsum eos exercitationem natus!",
    "Distinctio accusantium vitae, delectus omnis exercitationem nemo minus error ut laboriosam.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Vivamus gravida leo ut risus porttitor, ut rutrum arcu malesuada.",
    "Sed at enim ut lectus auctor placerat ac id lacus.",
    "Pellentesque pretium mauris a commodo scelerisque.",
    "Aliquam nec lorem quis turpis posuere dictum.",
    "Fusce a ipsum non dui aliquet feugiat ut a est.",
    "Proin efficitur erat at semper condimentum.",
    "Nullam nec tellus a metus scelerisque convallis.",
    "Ut tincidunt quam et mi volutpat, a consequat sapien interdum.",
    "Praesent dignissim ex id enim hendrerit ullamcorper.",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras auctor ante id orci tincidunt, id sagittis velit aliquet.",
    "Quisque sit amet leo bibendum, aliquam metus eget, consequat ligula.",
    "Nam ullamcorper nibh sed ante dictum, nec egestas nisi finibus.",
    "Phasellus sed metus condimentum, mattis odio id, fringilla sem.",
    "Praesent nec erat a orci gravida ultricies eu eu ipsum.",
    "Suspendisse non purus a magna gravida iaculis id eget nunc."
];